### ISSUE TITLE
-bash: ./test.sh: /bin/env: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by dariobuttari** [scottsimpson/commandlinebasics#2]
I was watching "Learning Linux Command Line" on Lynda.com, and I got issues at 4min 42s of the  "File Permission" video. At that point of the video it is shown how to run `./test.sh`, but I could not make it work on both ChromeOS and MacOs, and I got the following error instead:
`-bash: ./test.sh: /bin/env: bad interpreter: No such file or directory`

I searched online, and I found that on many systems `/bin/env` does not exist. I believe that in order to make the script compatible with more systems
`#!/bin/env bash`
should be replaced with
`#!/usr/bin/env bash`

After making that change I was able to execute `./test.sh` on both ChromeOS and MacOS with no issues.

**Comment by scottsimpson** [comment]
Good catch, thanks. This has been fixed.
